{
 "title": "Client Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Main",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Keynote",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Keynote_WLC" }
     ]
    },
    {
     "alias": "Meeting",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Meeting_WLC" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Main",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Keynote",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Keynote_WLC" }
     ]
    },
    {
     "alias": "Meeting",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Meeting_WLC" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Main",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Keynote",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Main",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Keynote",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "Meeting",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Meeting_WLC" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Main",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Keynote",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "Meeting",
     "measurement": "wlanSummary",
     "select": [
      [
       { "params": [ "wlanUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlanId::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "wlcName::tag", "operator": "=", "value": "Meeting_WLC" }
     ]
    }
   ]
  },
  {
   "title": "Total Wi-Fi Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$tag_wlcName",
     "groupBy": [
      { "params": [ "wlcName::tag" ], "type": "tag" }
     ],
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "clients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" },
      { "condition": "OR", "key": "wlcName::tag", "operator": "=", "value": "Keynote" },
      { "condition": "OR", "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    }
   ]
  },
  {
   "title": "Total Wi-Fi Clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Clients-Main",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "clients" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Clients-Keynote",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "clients" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "Clients-Meeting",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "clients" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    }
   ]
  },
  {
   "title": "Clients / Band",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Clients 2.4GHz",
     "measurement": "clientSummary",
     "select": [
      [
       { "params": [ "24ghzClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Clients 2.4GHz",
     "measurement": "clientSummary",
     "select": [
      [
       { "params": [ "24ghzClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "Clients 2.4GHz",
     "measurement": "clientSummary",
     "select": [
      [
       { "params": [ "24ghzClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "Clients 5GHz",
     "measurement": "clientSummary",
     "select": [
      [
       { "params": [ "5ghzClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Clients 5GHz",
     "measurement": "clientSummary",
     "select": [
      [
       { "params": [ "5ghzClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "Clients 5GHz",
     "measurement": "clientSummary",
     "select": [
      [
       { "params": [ "5ghzClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "Clients 6GHz",
     "measurement": "clientSummary",
     "select": [
      [
       { "params": [ "6ghzClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Clients 6GHz",
     "measurement": "clientSummary",
     "select": [
      [
       { "params": [ "6ghzClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "Clients 6GHz",
     "measurement": "clientSummary",
     "select": [
      [
       { "params": [ "6ghzClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    }
   ]
  },
  {
   "title": "Client States",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "authClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "authClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "authClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "authClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "authClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "authClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "mobilityClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "mobilityClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "mobilityClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "mobilityClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "mobilityClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "mobilityClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "ipLearnClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "ipLearnClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "ipLearnClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "ipLearnClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "ipLearnClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "ipLearnClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "webAuthClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "webAuthClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "webAuthClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "webAuthClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "webAuthClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "webAuthClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "runClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "runClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "runClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "runClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "runClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "runClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "deleteClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "deleteClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "deleteClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "deleteClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "deleteClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "deleteClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "randomMacClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "randomMacClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "randomMacClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "randomMacClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "randomMacClients",
     "measurement": "clientSummary",
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n",
     "select": [
      [
       { "params": [ "randomMacClients" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    }
   ]
  }
 ]
}