{
 "title": "Controller Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Port-Channel1 - Main",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Rx",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "rx" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "Tx",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "tx" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    }
   ]
  },
  {
   "title": "Port-Channel1 - Main",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "inErrors",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "inErrors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "outErrors",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "outErrors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "inDiscards",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "inDiscards" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "outDiscards",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "outDiscards" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    }
   ]
  },
  {
   "title": "WNCD - Main",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "WNCD 0",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "main-wlc" }
     ]
    },
    {
     "alias": "WNCD 1",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "main-wlc" }
     ]
    },
    {
     "alias": "WNCD 2",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "main-wlc" }
     ]
    },
    {
     "alias": "WNCD 3",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "main-wlc" }
     ]
    },
    {
     "alias": "WNCD 4",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_4" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "main-wlc" }
     ]
    },
    {
     "alias": "WNCD 5",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_5" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "main-wlc" }
     ]
    },
    {
     "alias": "WNCD 6",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_6" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "main-wlc" }
     ]
    },
    {
     "alias": "WNCD 7",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_7" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "main-wlc" }
     ]
    }
   ]
  },
  {
   "title": "HA - Main",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Model",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "model" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "SSO",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "sso" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    },
    {
     "alias": "Software",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "software" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Main" }
     ]
    }
   ]
  },
  {
   "title": "Port-Channel1 - Keynote",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Rx",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "rx" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "Tx",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "tx" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    }
   ]
  },
  {
   "title": "Port-Channel1 - Keynote",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "inErrors",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "inErrors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "outErrors",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "outErrors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "inDiscards",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "inDiscards" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "outDiscards",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "outDiscards" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    }
   ]
  },
  {
   "title": "WNCD - Keynote",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "WNCD 0",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "keynote-wlc" }
     ]
    },
    {
     "alias": "WNCD 1",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "keynote-wlc" }
     ]
    },
    {
     "alias": "WNCD 2",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "keynote-wlc" }
     ]
    },
    {
     "alias": "WNCD 3",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "keynote-wlc" }
     ]
    },
    {
     "alias": "WNCD 4",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_4" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "keynote-wlc" }
     ]
    },
    {
     "alias": "WNCD 5",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_5" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "keynote-wlc" }
     ]
    },
    {
     "alias": "WNCD 6",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_6" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "keynote-wlc" }
     ]
    },
    {
     "alias": "WNCD 7",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_7" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "keynote-wlc" }
     ]
    }
   ]
  },
  {
   "title": "HA - Keynote",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Model",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "model" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "SSO",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "sso" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    },
    {
     "alias": "Software",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "software" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Keynote" }
     ]
    }
   ]
  },
  {
   "title": "Port-Channel1 - Meeting",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Rx",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "rx" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "Tx",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "tx" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    }
   ]
  },
  {
   "title": "Port-Channel1 - Meeting Village",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "inErrors",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "inErrors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "outErrors",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "outErrors" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "inDiscards",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "inDiscards" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    },
    {
     "alias": "outDiscards",
     "measurement": "wlcInterfaces",
     "select": [
      [
       { "params": [ "outDiscards" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" },
      { "condition": "AND", "key": "intName::tag", "operator": "=", "value": "Port-channel1" }
     ]
    }
   ]
  },
  {
   "title": "WNCD - Meeting Village",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "WNCD 0",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "meeting-wlc" }
     ]
    },
    {
     "alias": "WNCD 1",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "meeting-wlc" }
     ]
    },
    {
     "alias": "WNCD 2",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "meeting-wlc" }
     ]
    },
    {
     "alias": "WNCD 3",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "meeting-wlc" }
     ]
    },
    {
     "alias": "WNCD 4",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_4" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "meeting-wlc" }
     ]
    },
    {
     "alias": "WNCD 5",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_5" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "meeting-wlc" }
     ]
    },
    {
     "alias": "WNCD 6",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_6" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "meeting-wlc" }
     ]
    },
    {
     "alias": "WNCD 7",
     "measurement": "wncd",
     "select": [
      [
       { "params": [ "wncd_7" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "meeting-wlc" }
     ]
    }
   ]
  },
  {
   "title": "HA - Meeting Village",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Model",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "model" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "SSO",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "sso" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    },
    {
     "alias": "Software",
     "measurement": "wlcInventory",
     "select": [
      [
       { "params": [ "software" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "wlcName::tag", "operator": "=", "value": "Meeting" }
     ]
    }
   ]
  }
 ]
}