{
 "title": "Wi-Fi Ninja",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Client metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Clients (All)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"connectedClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n\n    \n    \n"
    }
   ]
  },
  {
   "title": "Client Types (All)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Wi-Fi_6_(6GHz)\" or r[\"_field\"] == \"Wi-Fi_6_(5GHz)\" or r[\"_field\"] == \"Wi-Fi_6_(2.4GHz)\" or r[\"_field\"] == \"Wi-Fi_5\" or r[\"_field\"] == \"Wi-Fi_4_(5GHz)\" or r[\"_field\"] == \"Wi-Fi_4_(2.4GHz)\" or r[\"_field\"] == \"Wi-Fi_3\" or r[\"_field\"] == \"Wi-Fi_2\" or r[\"_field\"] == \"Wi-Fi_1\")\n  |> yield()"
    }
   ]
  },
  {
   "title": "Client States (All)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"authClients\" or r[\"_field\"] == \"deleteClients\" or r[\"_field\"] == \"ipLearnClients\" or r[\"_field\"] == \"mobilityClients\" or r[\"_field\"] == \"randomMacClients\" or r[\"_field\"] == \"runClients\" or r[\"_field\"] == \"webAuthClients\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()\n"
    }
   ]
  },
  {
   "title": "Connected Clients (Photographers)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\")\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\n  |> filter(fn: (r) => r[\"apName\"] == \"SBAPS1NCGRAW002\" or r[\"apName\"] == \"SBAPS1NCGRAW009\" or r[\"apName\"] == \"SBAPS1NDGRAW014\" or r[\"apName\"] == \"SBAPS1NDGRAW016\" or r[\"apName\"] == \"SBAPS1NDGRAW017\" or r[\"apName\"] == \"SBAPS1EDGRAW018\" or r[\"apName\"] == \"SBAPS1EDGRAW020\" or r[\"apName\"] == \"SBAPS1EDGRAW029\" or r[\"apName\"] == \"SBAPS1EDGRAW031\" or r[\"apName\"] == \"SBAPS1EAGRAW047\" or r[\"apName\"] == \"SBAPS1EAGRAW049\" or r[\"apName\"] == \"SBAPS1SBGRAW067\" or r[\"apName\"] == \"SBAPS1SBGRAW069\" or r[\"apName\"] == \"SBAPS1EAGRAW075\" or r[\"apName\"] == \"SBAPS1EAGRAW077\" or r[\"apName\"] == \"SBAPS1SAGRAW078\" or r[\"apName\"] == \"SBAPS1SAGRAW079\" or r[\"apName\"] == \"SBAPS1SAGRAW081\")\n  |> filter(fn: (r) => r[\"_field\"] == \"radioStas\")\n  |> yield()\n  "
    }
   ]
  },
  {
   "title": "Busy APs - Channel Utilization (Photographer APs)",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"radioUtil\")\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\" and r[\"radioState\"] == \"radio-up\")\n  |> filter(fn: (r) => r[\"apName\"] == \"SBAPS1NCGRAW002\" or r[\"apName\"] == \"SBAPS1NCGRAW009\" or r[\"apName\"] == \"SBAPS1NDGRAW014\" or r[\"apName\"] == \"SBAPS1NDGRAW016\" or r[\"apName\"] == \"SBAPS1NDGRAW017\" or r[\"apName\"] == \"SBAPS1EDGRAW018\" or r[\"apName\"] == \"SBAPS1EDGRAW020\" or r[\"apName\"] == \"SBAPS1EDGRAW029\" or r[\"apName\"] == \"SBAPS1EDGRAW031\" or r[\"apName\"] == \"SBAPS1EAGRAW047\" or r[\"apName\"] == \"SBAPS1EAGRAW049\" or r[\"apName\"] == \"SBAPS1SBGRAW067\" or r[\"apName\"] == \"SBAPS1SBGRAW069\" or r[\"apName\"] == \"SBAPS1EAGRAW075\" or r[\"apName\"] == \"SBAPS1EAGRAW077\" or r[\"apName\"] == \"SBAPS1SAGRAW078\" or r[\"apName\"] == \"SBAPS1SAGRAW079\" or r[\"apName\"] == \"SBAPS1SAGRAW081\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Busy APs - Clients (Photographer APs)",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\" and r[\"radioState\"] == \"radio-up\")\n  |> filter(fn: (r) => r[\"_field\"] == \"radioStas\")\n  |> filter(fn: (r) => r[\"apName\"] == \"SBAPS1NCGRAW002\" or r[\"apName\"] == \"SBAPS1NCGRAW009\" or r[\"apName\"] == \"SBAPS1NDGRAW014\" or r[\"apName\"] == \"SBAPS1NDGRAW016\" or r[\"apName\"] == \"SBAPS1NDGRAW017\" or r[\"apName\"] == \"SBAPS1EDGRAW018\" or r[\"apName\"] == \"SBAPS1EDGRAW020\" or r[\"apName\"] == \"SBAPS1EDGRAW029\" or r[\"apName\"] == \"SBAPS1EDGRAW031\" or r[\"apName\"] == \"SBAPS1EAGRAW047\" or r[\"apName\"] == \"SBAPS1EAGRAW049\" or r[\"apName\"] == \"SBAPS1SBGRAW067\" or r[\"apName\"] == \"SBAPS1SBGRAW069\" or r[\"apName\"] == \"SBAPS1EAGRAW075\" or r[\"apName\"] == \"SBAPS1EAGRAW077\" or r[\"apName\"] == \"SBAPS1SAGRAW078\" or r[\"apName\"] == \"SBAPS1SAGRAW079\" or r[\"apName\"] == \"SBAPS1SAGRAW081\")\n  |> last()"
    }
   ]
  },
  { "title": "AP metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Busy APs - Clients (All)",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\" and r[\"radioState\"] == \"radio-up\")\n  |> filter(fn: (r) => r[\"_field\"] == \"radioStas\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Busy APs - Channel Utilization (All)",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"radioUtil\")\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\" and r[\"radioState\"] == \"radio-up\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Channel Changes - 2.4 GHz",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf2ghz\")\r\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"radioChanges\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Channel Changes - 5 GHz",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf5ghz\")\r\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"radioChanges\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Channel Changes - 6 GHz",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"wifininja\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"rf6ghz\")\r\n  |> filter(fn: (r) => r[\"radioMode\"] == \"radio-mode-local\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"radioChanges\")\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "WLC metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data - IN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 2, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"inBytes\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "Data - OUT",
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"outBytes\")\n  |> filter(fn: (r) => r[\"wlcName\"] == \"WLC9800\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 0",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 2, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_0\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 1",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 6, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_1\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 2",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_2\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 3",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 14, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_3\")\n  |> yield()"
      }
     ]
    },
    {
     "title": "WNCD 4",
     "type": "gauge",
     "description": "5 Min",
     "gridPos": { "h": 7, "w": 4, "x": 18, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"wifininja\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wlcData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wncd_4\")\n  |> yield()"
      }
     ]
    }
   ]
  }
 ]
}